spring:
 datasource:
  username: codelex
  password: codelex
  url: jdbc:postgresql://localhost:5432/quiz_engine
 jpa:
  hibernate:
   ddl-auto: validate
 liquibase:
   change-log: classpath:/liquibase/liquibase.xml
   enabled: true
